---
# use debian-maintained docker package instead of Docker Inc. Community Edition (`docker-ce`) packages
docker_packages:
  - docker.io

# do not configure Docker Inc. apt repos
docker_add_repo: false

# docker-compose official releases are not built for arm64 until 2.0.1
docker_install_compose: false

docker_daemon_options:
  # use devicemapper for compatibility with NFS root
  storage-driver: devicemapper
  log-driver: journald
