---
- hosts: containerd_hosts
  roles:
    - ivan-c.containerd

- hosts: k8s_hosts
  roles:
    - geerlingguy.kubernetes
  post_tasks:
    - name: Stop and disable kubelet until kubeadm init
      service:
        name: kubelet
        state: stopped
        enabled: false
