---
- name: Install docker
  hosts: docker_hosts
  roles:
    - geerlingguy.docker
  post_tasks:
    - name: Install docker-compose from debian
      ansible.builtin.apt:
        name: docker-compose
        state: present

- name: Install kubernetes
  hosts: k8s_hosts
  roles:
    - geerlingguy.kubernetes
  post_tasks:
    - name: Stop and disable kubelet until kubeadm init
      ansible.builtin.service:
        name: kubelet
        state: stopped
        enabled: false
