---
- name: geerlingguy.docker
  src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.5.3

- name: geerlingguy.kubernetes
  src: https://github.com/geerlingguy/ansible-role-kubernetes
  version: 5.0.1
