---
- hosts: docker_hosts
  roles:
    - geerlingguy.docker
  post_tasks:
    - name: Install docker-compose from debian
      apt:
        name: docker-compose
        state: present

- hosts: k8s_hosts
  roles:
    - geerlingguy.kubernetes
  post_tasks:
    - name: Stop and disable kubelet until kubeadm init
      service:
        name: kubelet
        state: stopped
        enabled: false
